# Generated by Django 2.1.3 on 2018-11-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181117_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interested_list',
        ),
        migrations.AddField(
            model_name='profile',
            name='interested_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_profile.jpeg', upload_to='media/user/profile_images'),
        ),
    ]
