# Generated by Django 2.1.3 on 2018-11-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181121_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_profile.jpeg', upload_to='media/user/profile_images'),
        ),
    ]
