# Generated by Django 2.1.3 on 2018-11-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20181121_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='media/user/profile_images/default_profile.jpeg', upload_to='media/user/profile_images'),
        ),
    ]
