# Generated by Django 2.1.3 on 2018-12-11 13:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20181121_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interested_gigs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interested_html',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
