# Generated by Django 2.1.3 on 2019-02-22 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20181211_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_location',
        ),
    ]
