# Generated by Django 2.1.3 on 2019-02-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_spotify'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spotify',
        ),
    ]
