# Generated by Django 2.1.3 on 2019-02-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_spotify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interested_html',
        ),
    ]
