# Generated by Django 2.1.3 on 2019-03-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_profile_interested_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify',
            name='token',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
