# Generated by Django 2.1.3 on 2019-03-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190306_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotify',
            old_name='token',
            new_name='playlist_IDs',
        ),
    ]
