# Generated by Django 2.1.3 on 2019-03-06 16:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190306_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotify',
            name='user_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
