# Generated by Django 2.1.3 on 2019-03-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190307_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotify',
            name='recommended_artists',
            field=models.TextField(blank=True, null=True),
        ),
    ]
