# Generated by Django 2.1.3 on 2019-03-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_spotify_recommended_artists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_data',
            new_name='recommended_events',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='interested_gigs',
            new_name='saved_events',
        ),
    ]
