# Generated by Django 2.1.3 on 2019-03-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20190318_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify',
            name='recommended_artists',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
