# Generated by Django 2.1.3 on 2019-03-20 21:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190320_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recommended_events',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='saved_events',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='spotify',
            name='recommended_artists',
            field=models.TextField(blank=True, default=list, null=True),
        ),
    ]
