# Generated by Django 2.1.3 on 2019-03-20 22:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20190320_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify',
            name='recommended_artists',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
